### ISSUE TITLE
Merge with DevTools?

### ISSUE THREAD

**Issue by valdisiljuconoks** [jaytem/Episerver-LocalObjectCache#1]
it's been a while since I'm thinking about re-activated old Geta's plugin (CacheManager) and pull it into DeveloperTools. what do you think of this? maybe it's worth to unite and merge this code into dev tools? I see it would add value to the package..

**Comment by joemayberry** [comment]
Hi Validis, I think that would be a great idea. Would you want me to add it into the code, and create a pull request?

**Comment by valdisiljuconoks** [comment]
awesome! yes branch it. I have couple features to add to cancel view as well. then we can create PR

**Comment by joemayberry** [comment]
Cool. I'll see if I can get it to work. Thanks.

**Comment by joemayberry** [comment]
HI Validis, 

I think I have the local object cache incorporated into the DeveloperTools code, and working locally. I have a branch for the DeveloperTools repo, but I can't push that to the Github repo. How would you like me to proceed?

Thanks,
Joe Mayberry

**Comment by valdisiljuconoks** [comment]
blah, I'm an idiot. by branching I mean forking ;) I'll switch to your repo

**Comment by joemayberry** [comment]
That makes sense. I haven't ever done that, but I will, and check my changes into the fork. Thanks.

**Comment by joemayberry** [comment]
Hi Validis.

You should have an invitation for Github jaytem/DeveloperTools (https://github.com/jaytem/DeveloperTools), with the Local Object Cache integrated on the LocalObjectCache branch.

Hopefully I have everything right now. This was the first time I have tried to fork a repo.

Thanks,
Joe Mayberry

**Comment by valdisiljuconoks** [comment]
PR is in progress :) thx for contributing

**Comment by valdisiljuconoks** [comment]
hope you didn't mind tiny code clean-ups and refactorings tho..
